// Mocks generated by Mockito 5.4.4 from annotations
// in maids_task/test/features/Todo/cubit/todo_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:maids_task/core/network/network_layer.dart' as _i2;
import 'package:maids_task/features/todo/repos/todo_repo.dart' as _i4;
import 'package:maids_task/Model/todo_model.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkService_0 extends _i1.SmartFake
    implements _i2.NetworkService {
  _FakeNetworkService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i4.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NetworkService get networkService => (super.noSuchMethod(
        Invocation.getter(#networkService),
        returnValue: _FakeNetworkService_0(
          this,
          Invocation.getter(#networkService),
        ),
      ) as _i2.NetworkService);

  @override
  _i5.Future<_i3.Either<String, List<_i6.Todo>>> fetchTodos({
    int? limit = 10,
    int? skip = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchTodos,
          [],
          {
            #limit: limit,
            #skip: skip,
          },
        ),
        returnValue: _i5.Future<_i3.Either<String, List<_i6.Todo>>>.value(
            _FakeEither_1<String, List<_i6.Todo>>(
          this,
          Invocation.method(
            #fetchTodos,
            [],
            {
              #limit: limit,
              #skip: skip,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<String, List<_i6.Todo>>>);

  @override
  _i5.Future<_i3.Either<String, _i6.Todo>> addTodo(_i6.Todo? todo) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTodo,
          [todo],
        ),
        returnValue: _i5.Future<_i3.Either<String, _i6.Todo>>.value(
            _FakeEither_1<String, _i6.Todo>(
          this,
          Invocation.method(
            #addTodo,
            [todo],
          ),
        )),
      ) as _i5.Future<_i3.Either<String, _i6.Todo>>);

  @override
  _i5.Future<_i3.Either<String, _i6.Todo>> updateTodo(_i6.Todo? todo) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTodo,
          [todo],
        ),
        returnValue: _i5.Future<_i3.Either<String, _i6.Todo>>.value(
            _FakeEither_1<String, _i6.Todo>(
          this,
          Invocation.method(
            #updateTodo,
            [todo],
          ),
        )),
      ) as _i5.Future<_i3.Either<String, _i6.Todo>>);

  @override
  _i5.Future<_i3.Either<String, void>> deleteTodo(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTodo,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<String, void>>.value(
            _FakeEither_1<String, void>(
          this,
          Invocation.method(
            #deleteTodo,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<String, void>>);
}
